@baseUrl = https://localhost:7098

### CADASTRAR CONTATOS
# @name cadastrarContato
POST {{baseUrl}}/api/contatos
Content-Type: application/json

{
    "nome": "Junior Testes",
    "email": "teste-{{$guid}}@academiadoprogramador.net",
    "telefone": "(11) 99999-0000",
    "cargo": "Analista de Testes",
    "empresa": "Academia do Programador"
}

### LISTAR CONTATOS
GET {{baseUrl}}/api/contatos

@contatoId = {{cadastrarContato.response.body.$.id}}

### SELECIOANR CONTATO POR ID
GET {{baseUrl}}/api/contatos/{{contatoId}}

