@baseUrl = https://localhost:7098

### Cadastrar contato
# @name cadastrarContato
POST {{baseUrl}}/api/contatos
Content-Type: application/json

{
    "nome": "P",
    "email": "teste-{{$guid}}academiadoprogramador.net",
    "telefone": "(11) 999-0770",
    "cargo": "Analista de Testes",
    "empresa": "Academia do Programador"
}

###
@contatoId = {{cadastrarContato.response.body.$.id}}

### Editar contato
PUT {{baseUrl}}/api/contatos/{{contatoId}}
Content-Type: application/json

{
    "nome": "Peter Testes Atualizado",
    "email": "teste-atualizado-{{$guid}}@academiadoprogramador.net",
    "telefone": "(11) 98388-3030",
    "cargo": "Staff Software Engineer",
    "empresa": "Academia do Programador"
}

### Excluir contato
DELETE {{baseUrl}}/api/contatos/{{contatoId}}

### Listar contatos
GET {{baseUrl}}/api/contatos

### Selecionar contato por ID
GET {{baseUrl}}/api/contatos/{{contatoId}}
